Refine/Controllers/ANRPC/AnrpcController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Refine.Repositories.IRepository;
using RefineModels.Models;
using RefineModels.Models.ANRPC;
 
namespace Refine.ANRPC.Controllers
{
    //[Authorize(Roles = "Anrpc")]
    public class AnrpcController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public AnrpcController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int id)
        {
            ViewBag.id = id;
            return View(_unitOfWork.Anrpc);
        }
        public IActionResult Categories()
        {
            return View("AnrpcCategories", _unitOfWork.Anrpc);
        }

        [HttpPost]
        public IActionResult UpdateAll([FromBody] List<UpdateItemDto> updatedItems)
        {
            if (ModelState.IsValid)
            {
                foreach (var updateItem in updatedItems)
                {
                    List<AnrpcBase> AllTables = new List<AnrpcBase>();

                    AnrpcTable1 firstTableEntity = _unitOfWork.Anrpc.GetEntityById<AnrpcTable1>(updateItem.Id);
                    AnrpcTable2 secondTableEntity = _unitOfWork.Anrpc.GetEntityById<AnrpcTable2>(updateItem.Id);
                    AnrpcTable3 thirdTableEntity = _unitOfWork.Anrpc.GetEntityById<AnrpcTable3>(updateItem.Id);
                    AnrpcTable4 FourthTableEntity = _unitOfWork.Anrpc.GetEntityById<AnrpcTable4>(updateItem.Id);
                    AllTables.Add(firstTableEntity);
                    AllTables.Add(secondTableEntity);
                    AllTables.Add(thirdTableEntity);
                    AllTables.Add(FourthTableEntity);
 
                    // ssuming _AnrpcViewRepository.GetEntityById<T> returns null if the entity is not found.
                    foreach (var table in AllTables)
                    {
                        if (updatedItems != null)
                        {
                            if (table != null)
                            {
                                _unitOfWork.Anrpc.UpdateEntity(table, updateItem);
                            }

                        }
                    }
                }
            }
            // Return appropriate IActionResult here, e.g., Ok() or BadRequest()
            return RedirectToAction("Index");
            // Also, make sure to handle errors and return the appropriate response if the ModelState is not valid.
        }



    }
}

Refine/Views/Shared/AsrPartial.cshtml
@model IEnumerable<dynamic>

@{
    Type itemType = Model.First().GetType(); // Assuming the items are not empty
}

<table class="table table-hover table-bordered rounded-table table table-hover">
    <thead>
        <tr class="table-light text-center">
           
            <th class="text-center"></th>
            @foreach (var propertyInfo in itemType.GetProperties().Reverse())
            {
                if (propertyInfo.Name != "Id")
                {
                    var displayNameAttribute = propertyInfo.GetCustomAttributes(typeof(DisplayAttribute), true)
                    .FirstOrDefault() as DisplayAttribute;

                    string displayName = displayNameAttribute?.Name ?? propertyInfo.Name;
                   
                    <th class="text-center">
                        @displayName
                    </th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="table-secondary text-center">
                <th></th>
           @*      <td class="text-center">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Category" asp-action="Delete">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </td> *@
                @foreach (var propertyInfo in itemType.GetProperties().Reverse())
                {
                    if (propertyInfo.Name != "Id")
                    {
                        var value = item.GetType().GetProperty(propertyInfo.Name)?.GetValue(item);
                        <td contenteditable="true" class="editable" data-id="@item.Id" data-field="@propertyInfo.Name">@((value != null) ? value.ToString() : "")</td>
                    }
                     
                }
                
            </tr>
        }
    </tbody>
</table>

Refine/Views/Shared/_CategoriesLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Festava Live - Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <link href="/css/bootstrap-icons.css" rel="stylesheet">

    <link href="/css/templatemo-festava-live.css" rel="stylesheet">

    <!--

    TemplateMo 583 Festava Live

    https://templatemo.com/tm-583-festava-live

    -->
</head>

<body>

    <main>
 


        <section class="hero-section" id="section_1">
            <div b-arldui0g2v="" class="section-overlay"></div>
            <div class="container d-flex justify-content-center align-items-center">

                <div class="row">
                    @RenderBody()


                    <div class="col-lg-12 col-12 mt-auto d-flex flex-column flex-lg-row text-center">
                    </div>
                </div>
            </div>

            <div class="video-wrap">
                <video autoplay="" loop="" muted="" class="custom-video" poster="">
                    <source src="/video/pexels-kelly-lacy-9339478 (2160p).mp4" type="video/mp4">

                    Your browser does not support the video tag.
                </video>
            </div>
        </section>





 
    </main>
    <!--

    T e m p l a t e M o

    -->
    <!-- JAVASCRIPT FILES -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script src="/js/click-scroll.js"></script>
    <script src="/js/custom.js"></script>

</body>

</html>

Refine/Views/Shared/_HomeLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Festava Live - Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/bootstrap-icons.css" rel="stylesheet">

    <link href="css/templatemo-festava-live.css" rel="stylesheet">

    <!--

TemplateMo 583 Festava Live

https://templatemo.com/tm-583-festava-live

-->
</head>

<body>

    <main>

        


        

        @RenderBody()
        <section class="hero-section" id="section_1">
            <div class="section-overlay"></div>

            <div class="container d-flex justify-content-center align-items-center">
             
                <div class="row">

                    <div class="col-12 mt-auto mb-5 text-center">
                        
                            <h1 class="text-white mb-1">اهلا وسهلا بكم في التقارير اليومية</h1>
                            <h1 class="text-white mb-5">للهيئة العامة للبترول</h1>
 
                        <a class="btn custom-btn smoothscroll infobtn mt-5" asp-controller="Anrpc" asp-action="Categories">استمرار بدون تسجيل دخول</a>
                        
                        <a class="btn custom-btn smoothscroll loginbtn mt-5" asp-controller="Account" asp-action="AdvanceLogin">تسجيل الدخول</a>
                      
                    </div>
               
                </div>
            </div>

            <div class="video-wrap">
                <video autoplay="" loop="" muted="" class="custom-video" poster="">
                    <source src="/video/pexels-kelly-lacy-9339478 (2160p).mp4" type="video/mp4">

                    Your browser does not support the video tag.
                </video>
            </div>
        </section>


        


        


        


        


        
    </main>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Refine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Refine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Refine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Refine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Refine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Refine/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Festava Live - Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <link href="/css/bootstrap-icons.css" rel="stylesheet">

    <link href="/css/templatemo-festava-live.css" rel="stylesheet">

    <!--

    TemplateMo 583 Festava Live

    https://templatemo.com/tm-583-festava-live

    -->
</head>

<body>

    <main>
 


        <section class="hero-section" id="section_1">
            <div b-arldui0g2v="" class="section-overlay"></div>
            <div class="container d-flex justify-content-center align-items-center">

                <div class="row">
                    @RenderBody()


                    <div class="col-lg-12 col-12 mt-auto d-flex flex-column flex-lg-row text-center">
                    </div>
                </div>
            </div>

            <div class="video-wrap">
                <video autoplay="" loop="" muted="" class="custom-video" poster="">
                    <source src="/video/pexels-kelly-lacy-9339478 (2160p).mp4" type="video/mp4">

                    Your browser does not support the video tag.
                </video>
            </div>
        </section>





 
    </main>
    <!--

    T e m p l a t e M o

    -->
    <!-- JAVASCRIPT FILES -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script src="/js/click-scroll.js"></script>
    <script src="/js/custom.js"></script>

</body>

</html>

Refine/Views/Shared/_MyLayout.cshtml
<!doctype html>
<html lang="en">
    
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Festava Live - Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet">

    <link href="/css/bootstrap.min.css" rel="stylesheet">
                
    <link href="/css/bootstrap-icons.css" rel="stylesheet">
              
    <link href="/css/templatemo-festava-live.css" rel="stylesheet">

    <!--

TemplateMo 583 Festava Live

https://templatemo.com/tm-583-festava-live

-->
</head>

<body>

    <main>

        <header b-x42msg3eh7="">
            <nav b-x42msg3eh7="" class="navbar navbar-expand-lg">
                <div b-x42msg3eh7="" class="container">
                    <a b-x42msg3eh7="" class="navbar-brand" href="index.html">
                        Reports
                    </a>

@*                     <a b-x42msg3eh7="" href="ticket.html" class="btn custom-btn d-lg-none ms-auto me-4">Buy Ticket</a>
 *@
@*                     <button b-x42msg3eh7="" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span b-x42msg3eh7="" class="navbar-toggler-icon"></span>
                    </button>
 *@@* 
                    <div b-x42msg3eh7="" class="collapse navbar-collapse" id="navbarNav">
                        <ul b-x42msg3eh7="" class="navbar-nav align-items-lg-center ms-auto me-lg-5">
                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll active" href="#section_1">Home</a>
                            </li>

                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll inactive" href="#section_2">About</a>
                            </li>

                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll inactive" href="#section_3">Artists</a>
                            </li>

                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll inactive" href="#section_4">Schedule</a>
                            </li>

                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll inactive" href="#section_5">Pricing</a>
                            </li>

                            <li b-x42msg3eh7="" class="nav-item">
                                <a b-x42msg3eh7="" class="nav-link click-scroll inactive" href="#section_6">Contact</a>
                            </li>
                        </ul>

                        <a b-x42msg3eh7="" href="ticket.html" class="btn custom-btn d-lg-block d-none">Buy Ticket</a>
                    </div> *@
                </div>
            </nav>
        </header>

       

        <section class="hero-section" id="section_1">
           
            <div class="container d-flex justify-content-center align-items-center">
                 
                <div class="row">
                    @RenderBody() 
        

                    <div class="col-lg-12 col-12 mt-auto d-flex flex-column flex-lg-row text-center">
                    

                      

                    </div>
                </div>
            </div>
            <div class="video-wrap">
                <video autoplay="" loop="" muted="" class="custom-video" poster="">
                    <source src="/video/pexels-kelly-lacy-9339478 (2160p).mp4" type="video/mp4">

                    Your browser does not support the video tag.
                </video>
            </div>v>
        </section>


      



    <footer class="site-footer">
      @*   <div class="site-footer-top">
            <div class="container">
                <div class="row">

                    

               
              
      </div>
                </div>
            </div>
        </div> *@
        <div class="container">
            <div class="row">

            @*     <div class="col-lg-6 col-12 mb-4 pb-2">
                    <h5 class="site-footer-title mb-3">Links</h5>

                    <ul class="site-footer-links">
                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Home</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">About</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Artists</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Schedule</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Pricing</a>
                        </li>

                        <li class="site-footer-link-item">
                            <a href="#" class="site-footer-link">Contact</a>
                        </li>
                    </ul>
                </div> *@

         @*        <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <h5 class="site-footer-title mb-3">Have a question?</h5>

                    <p class="text-white d-flex mb-1">
                        <a href="tel: 090-080-0760" class="site-footer-link">
                            090-080-0760
                        </a>
                    </p>

                    <p class="text-white d-flex">
                        <a href="mailto:hello@company.com" class="site-footer-link">
                            hello@company.com
                        </a>
                    </p>
                </div> *@
@* 
                <div class="col-lg-3 col-md-6 col-11 mb-4 mb-lg-0 mb-md-0">
                    <h5 class="site-footer-title mb-3">Location</h5>

                    <p class="text-white d-flex mt-3 mb-2">
                        Silang Junction South, Tagaytay, Cavite, Philippines</p>

                    <a class="link-fx-1 color-contrast-higher mt-3" href="#">
                        <span>Our Maps</span>
                        <svg class="icon" viewBox="0 0 32 32" aria-hidden="true">
                            <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
                                <circle cx="16" cy="16" r="15.5"></circle>
                                <line x1="10" y1="18" x2="16" y2="12"></line>
                                <line x1="16" y1="12" x2="22" y2="18"></line>
                            </g>
                        </svg>
                    </a>
                </div> *@
            </div>
        </div>

        <div class="site-footer-bottom">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-12 mt-5">
                  @*       <p class="copyright-text">Copyright © 2036 Festava Live Company</p>
                        <p class="copyright-text">Distributed by: <a href="https://themewagon.com">ThemeWagon</a></p> *@
                    </div>

                    <div class="col-lg-8 col-12 mt-lg-5">
                   @*      <ul class="site-footer-links">
                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Terms &amp; Conditions</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Privacy Policy</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Your Feedback</a>
                            </li>
                        </ul> *@
                    </div>
                </div>
            </div>
        </div>
    </footer>
    </main>
    <!--

T e m p l a t e M o

-->

    <!-- JAVASCRIPT FILES -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
 
    <script src="/js/click-scroll.js"></script>
    <script src="/js/custom.js"></script>

</body>

</html>